# Generated by Django 6.1 on 2026-09-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(help_text='Se usa en la URL, por ejemplo: adulto-mayor', max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'tipo de amenaza',
                'verbose_name_plural': 'tipos de amenaza',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(help_text='La situación y la pregunta que ve el usuario.')),
                ('medio', models.CharField(choices=[('sms', 'SMS'), ('correo', 'Correo electrónico'), ('llamada', 'Llamada telefónica'), ('whatsapp', 'WhatsApp'), ('redes', 'Redes sociales'), ('web', 'Sitio web'), ('wifi', 'Red Wi-Fi'), ('presencial', 'Presencial / equipo compartido'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('mensaje_simulado', models.TextField(blank=True, help_text='Opcional: texto del SMS, correo o mensaje falso que se le muestra al usuario.')),
                ('explicacion', models.TextField(blank=True, help_text='Por qué la respuesta correcta es la más segura.')),
                ('puntos', models.PositiveSmallIntegerField(default=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='contenido.perfil')),
                ('tipo_amenaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='contenido.tipoamenaza')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['perfil', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('es_correcta', models.BooleanField(default=False)),
                ('retroalimentacion', models.TextField(blank=True, help_text='Opcional: qué pasa si el usuario elige esta opción.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='contenido.pregunta')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'ordering': ['pregunta', 'orden', 'id'],
            },
        ),
    ]
